# Generated by Django 4.2.5 on 2023-09-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='shia_app_file',
        ),
    ]
