# Generated by Django 4.2.5 on 2023-09-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0002_alter_file_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='Resource_name',
            new_name='resource_name',
        ),
        migrations.RenameField(
            model_name='edit',
            old_name='Task',
            new_name='task',
        ),
    ]
