# Generated by Django 4.2.5 on 2023-09-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0003_rename_resource_name_edit_resource_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='progress',
            new_name='Progress',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='Status',
        ),
    ]
