# Generated by Django 4.2.5 on 2023-09-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0004_rename_progress_status_progress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status',
            new_name='project_status',
        ),
    ]
