# Generated by Django 4.2.5 on 2023-09-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0005_rename_status_project_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project_status',
            new_name='status_update',
        ),
    ]
