# Generated by Django 4.2.5 on 2023-09-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0006_rename_project_status_status_update'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status_update',
            table='shia_app_status_update',
        ),
    ]
