# Generated by Django 4.2.5 on 2023-09-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0007_alter_status_update_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status_update',
            table=None,
        ),
    ]
