# Generated by Django 4.2.5 on 2023-09-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0008_alter_status_update_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status_update',
            table='shia_app_status_update',
        ),
    ]
