# Generated by Django 4.2.5 on 2023-09-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0009_alter_status_update_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projectdetails',
            new_name='projectdetail',
        ),
    ]
