# Generated by Django 4.2.5 on 2023-10-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0010_rename_projectdetails_projectdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.CharField(max_length=10)),
                ('emp_id', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('join_date', models.DateField()),
                ('super_user', models.BooleanField(default=False)),
                ('profile_image_base64', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
