# Generated by Django 4.2.5 on 2023-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emp_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_base64',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='super_user',
            field=models.BooleanField(),
        ),
    ]
