# Generated by Django 4.2.5 on 2023-10-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0013_alter_userprofile_email_alter_userprofile_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
