# Generated by Django 4.2.5 on 2023-10-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0015_alter_userprofile_dob_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='super_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
