# Generated by Django 4.2.5 on 2023-10-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shia_app', '0016_alter_userprofile_super_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='log',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
